from enum import Enum


class Identifier(Enum):
    IDENTIFIER_USER = "USER"
    IDENTIFIER_OWNER = "OWNER"


class SourceType(Enum):
    SOURCE_PRIVATE = "PRIVATE"
    SOURCE_GROUP = "GROUP"


class EventType(Enum):
    EVENT_META = "META"
    EVENT_MESSAGE = "MESSAGE"
    EVENT_MESSAGE_SENT = "MESSAGE_SENT"
    EVENT_REQUEST = "REQUEST"
    EVENT_NOTICE = "NOTICE"


class MessageType(Enum):
    MESSAGE_TEXT = "TEXT"
    MESSAGE_FACE = "FACE"
    MESSAGE_IMAGE = "IMAGE"
    MESSAGE_RECORD = "RECORD"
    MESSAGE_VIDEO = "VIDEO"
    MESSAGE_MUSIC = "MUSIC"
    MESSAGE_AT = "AT"
    MESSAGE_RPS = "RPS"
    MESSAGE_FILE = "FILE"
    MESSAGE_DICE = "DICE"
    MESSAGE_SHAKE = "SHAKE"
    MESSAGE_POKE = "POKE"
    MESSAGE_SHARE = "SHARE"
    MESSAGE_LOCATION = "LOCATION"
    MESSAGE_CONTACT = "CONTACT"
    MESSAGE_IMPRESSION = "IMPRESSION"
    MESSAGE_REPLY = "REPLY"
    MESSAGE_FORWARD = "FORWARD"
    MESSAGE_NODE = "NODE"
    MESSAGE_JSON = "JSON"
    MESSAGE_MFACE = "MFACE"
    MESSAGE_MARKDOWN = "MARKDOWN"
    MESSAGE_LIGHTAPP = "LIGHTAPP"
